INSERT INTO tools_core.module (
    code,
    name,
    description,
    is_active
)
VALUES (
    'TOOLS_DOFUS',
    'Dofus',
    'Module pour l''outil Dofus',
    TRUE
);

INSERT INTO tools_dofus.category (id, name)
VALUES (0, 'UNKNOWN')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- tools_dofus: rendre les PK "id" auto-générées (IDENTITY)
-- ============================================================

-- game_version.id
ALTER TABLE tools_dofus.game_version
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- game_server.id
ALTER TABLE tools_dofus.game_server
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- category.id
ALTER TABLE tools_dofus.category
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- item_type.id
ALTER TABLE tools_dofus.item_type
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- item.id (INT8)
ALTER TABLE tools_dofus.item
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- item_image.id (INT8)
ALTER TABLE tools_dofus.item_image
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- recipe.id (INT8)
ALTER TABLE tools_dofus.recipe
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- item_price_user.id (INT8)
ALTER TABLE tools_dofus.item_price_user
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
