-- ajout des catégories à la main
INSERT INTO tools_dofus.category (id, name) VALUES
(1, 'Amulette'),
(2, 'Arme'),
(3, 'Anneau'),
(4, 'Ceinture'),
(5, 'Bottes'),
(6, 'Consommable'),
(7, 'Bouclier'),
(9, 'Ressource'),
(10, 'Chapeau'),
(11, 'Cape'),
(12, 'Familier'),
(13, 'Dofus / Trophée'),
(14, 'Objet de quête'),
(15, 'Mutation'),
(16, 'Nourriture'),
(17, 'Bénédiction'),
(18, 'Malédiction'),
(19, 'Bonus de jeu de rôle'),
(20, 'Suiveur'),
(22, 'Cosmétiques'),
(23, 'Compagnon'),
(24, 'Equipement de monture'),
(25, 'Costume'),
(26, 'Certificat'),
(27, 'Fantôme de familier'),
(69, 'unknown type 69'),
(70, 'unknown type 70');
